spring:
  profiles:
    active: dev
  datasource:
    initialization-mode: never
  liquibase:
    enabled: false

logging.level.root: info
logging.level.org.jooq: debug

---
spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3316/sample
    username: root
    password: password

---
spring:
  profiles: production
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

grpc:
  port: 6565
